/*
 *  Avis event router.
 *  
 *  Copyright (C) 2008 Matthew Phillips <avis@mattp.name>
 *
 *  This program is free software: you can redistribute it and/or
 *  modify it under the terms of the GNU General Public License
 *  version 3 as published by the Free Software Foundation.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
/* Generated By:JavaCC: Do not edit this line. SubscriptionParserConstants.java */
package org.avis.subscription.parser;

public interface SubscriptionParserConstants {

  int EOF = 0;
  int IDENTIFIER = 5;
  int LETTER = 6;
  int ID_CHAR = 7;
  int BACKSLASH = 8;
  int INTEGER_LITERAL = 9;
  int DECIMAL_LITERAL = 10;
  int HEX_LITERAL = 11;
  int HEX_DIGIT = 12;
  int OCTAL_LITERAL = 13;
  int REAL_LITERAL = 14;
  int EXPONENT = 15;
  int STRING_LITERAL = 16;
  int DQUOTE_STRING_LITERAL = 17;
  int SQUOTE_STRING_LITERAL = 18;
  int BACKSLASH_EXPR = 19;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<ID_CHAR>",
    "<BACKSLASH>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<HEX_DIGIT>",
    "<OCTAL_LITERAL>",
    "<REAL_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "<DQUOTE_STRING_LITERAL>",
    "<SQUOTE_STRING_LITERAL>",
    "<BACKSLASH_EXPR>",
    "\"||\"",
    "\"^^\"",
    "\"&&\"",
    "\"!\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\"-\"",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"~\"",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
